### ISSUE TITLE
Using radar to obtain point cloud data

### ISSUE THREAD

**Issue by tristeph** [yizzfz/mmRadarVision#1]
Hello, I am very interested in your project content. I have an IWR 1843 radar at hand. According to your description of collecting point cloud data, I found the User&Data port of my device and modified the port in config.py. Since I only have one radar device, I only kept one data in RADAR-CFG. Then, I modified radar_to_use to radar_to_use=[0] in demo. py, and ran Python demo. py. The result is:
[1843] Connected
[Visualizer AE] start
Waiting for data
Waiting for data
Waiting for data
[1843] All cfg sent
[1843] Sensor start
Waiting for data
Like many [Visualizer_AE] Waiting for data's, it's because I haven't configured it properly
Can you give me some help?

**Comment by yizzfz** [comment]
I just realized there are some leftover merge logs in the 1843.cfg file that I forgot to delete. Try 6a998454a3d143af2c70add66ea73814c3b2bee7.

Have you tried the TI mmWave Demo Visualizer mentioned on the readme page, just to make sure the hardware, the firmware and the driver are all functioning properly?

**Comment by tristeph** [comment]
Thank you for your reply！
I have noticed that I may not have been running according to the display requirements of TI mmWave Demo Visualizer. Also, as you mentioned in your introduction (the TI out of box demo firmware), is this firmware out-of-box_1843_isk?

**Comment by tristeph** [comment]
> I just realized there are some leftover merge logs in the 1843.cfg file that I forgot to delete. Try [6a99845](https://github.com/yizzfz/mmRadarVision/commit/6a998454a3d143af2c70add66ea73814c3b2bee7).
> 
> Have you tried the TI mmWave Demo Visualizer mentioned on the readme page, just to make sure the hardware, the firmware and the driver are all functioning properly?

Thank for your reply,Now I can run the program on my device.
